// Generated by CoffeeScript 1.8.0

/* 
	Parse Cloud code for HackFSU-test
	
	To update, follow this: https://www.parse.com/docs/cloud_code_guide#started
	Must be manually converted into .js
	global.json is required (gitignored, see Jared)

EXAMPLE:

Parse.Cloud.define "hello", (req, res)->
  res.success "Hello world!"
 */
Parse.Cloud.define("getAllConfirmationIds", function(req, res) {
  var query;
  Parse.Cloud.useMasterKey();
  query = new Parse.Query('Applications');
  query.limit(1000);
  query.find({
    success: function(results) {
      var app, ids, _i, _len;
      ids = [];
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        app = results[_i];
        if ((app.get('confirmationId')) != null) {
          ids.push(app.get('confirmationId'));
        }
      }
      res.success(ids);
    },
    error: function(error) {
      res.error(error);
    }
  });
});


/*
	Checks if a confirmation id is valid.
	if it is, result = 
		valid: true
		objectId: (string)
		firstName: (string)
		lastName: (string)
		hasDiet: (boolean)		#if we have data on their diet question
		status: (string)
	if it isnt, result =
		valid: false
 */

Parse.Cloud.define("getAppSimpleByConfirmationId", function(req, res) {
  var query;
  Parse.Cloud.useMasterKey();
  query = new Parse.Query('Applications');
  query.equalTo('confirmationId', req.params.confirmationId);
  query.limit(1);
  query.find({
    success: function(results) {
      if (results.length === 0) {
        res.success({
          valid: false
        });
      } else {
        res.success({
          valid: true,
          objectId: results[0].get('objectId'),
          firstName: results[0].get('firstName'),
          lastName: results[0].get('lastName'),
          hasDiet: (results[0].get('QAs'))[3].trim() != null,
          status: results[0].get('status')
        });
      }
    },
    error: function(error) {
      res.error(error);
    }
  });
});
