/**
* Email model
*
* Autogenerated by modelify.js.
* TODO: Add your own documentation for this file here.
*/

'use strict';

export default function (app) {
	const PARSE_CLASSNAME = 'Email';

	const Parse = app.Parse;
	const _ = app._;
	const validate = app.validate;

	class Email extends Parse.Object {
		constructor(o) {
			super(PARSE_CLASSNAME);

			o = validate(o, _.isObject);
			this.name = validate(o.name, name => {
				return !!name && _.isString(name);
			});
			this.content = validate(o.content, _.isArray);
			this.message = validate(o.message, message => {
				return !!message && _.isObject(message);
			});
			this.async = validate(o.async, async => {
				return !!async && _.isBoolean(async);
			});
			this.ip_pool = validate(o.ip_pool, ip_pool => {
				return !!ip_pool && _.isString(ip_pool);
			});
			this.description = validate(o.description, description => {
				return !!description && _.isString(description);
			});
			this.sendto = validate(o.sendto, sendto => {
				return !!sendto && _.isString(sendto);
			});

			this.set('name', this.name);
			this.set('content', this.content);
			this.set('message', this.message);
			this.set('async', this.async);
			this.set('ip_pool', this.ip_pool);
			this.set('description', this.description);
			this.set('sendto', this.sendto);
		}
	}

	app.model.Email = Email;
	Parse.Object.registerSubclass(PARSE_CLASSNAME, Email);
}
